baseURL: https://rebeccamanning.netlify.app/
languageCode: en-US
title: An Introduction - Rebecca Manning
theme: hugo-split-theme
disableKinds:
  - section
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap
relativeURLs: yes
uglyURLs: yes
copyright: '&copy;2021 Rebecca Manning'
params:
  author: Rebecca Manning
  description: Dynamic Intellect who Excels in Designing and Implementing Innovative Solutions
  links:
    - list1:
        heading: Connect
        link:
          - text: Linkedin
            url: 'https://www.linkedin.com/in/rebeccamanning422'
          - text: Professional Email
            url: 'https://rdm124@case.edu'
          - text: Personal Email 
            url: 'https://rdmannin@yahoo.com'
    - list2:
        heading: Collaborate
        link:
          - text: H.E.A.L
            url: 'https://sites.google.com/case.edu/heal/welcome'
          - text: KAH Cle
            url: 'http://kahcleveland.weebly.com/contact-us.html'
          - text: EHS
            url: 'https://case.edu/ehs/about/staff'
    - list3:
        heading: Contribute
        link:
          - text: Volunteer
            url: 'http://kahcleveland.weebly.com/events.html'
          - text: Donate
            url: 'https://www.paypal.com/donate?token=3Cbr3ROxbxJpRjVvyZr0o2-gWZAEQZuiExuQfGGqJ-Y7Sh9mCKNAQmhxwH9MHLfKApNS1F7FV64MgXZR'
          - text: H.E.A.L Advocates
            url: 'https://sites.google.com/case.edu/heal/advocates/become-an-advocate?authuser=0'
  shareImage: images/IMG_1729.jpg
  twitterHandle: 
  visual:
    image:
      enable: yes
      file: images/IMG_1729.jpg
      position: center center
    video:
      enable: no
      file: videos/background.mp4
      mute: yes
